### ISSUE TITLE
Any related publication?

### ISSUE THREAD

**Issue by ranbix666** [njetzel/ngc#3]
Hi Nick, thank you for sharing this very useful package. I just wonder if there is a related paper to check the results and algorithm. I found a "lassoGranger" by A. Arnold, Y. Liu, and N. Abe. Temporal causal modeling with graphical granger methods. In KDD, 2007. However, I am not sure if it is the same (they wrote their code in matlab).

**Comment by njetzel** [comment]
Hi,
It was primarily based on these two papers: http://faculty.washington.edu/ashojaie/papers/TruncLasso4GGC.pdf
http://faculty.washington.edu/ashojaie/papers/ThrshLasso4GGC.pdf

**Comment by ranbix666** [comment]
Thank you!
